package constants

// Central log templates referenced across the whole backend.
const (
	LogUserRegisterSuccess      = "user register success: username=%s"
	LogUserRegisterFailed       = "user register failed: username=%s"
	LogUserLoginSuccess         = "user login success: username=%s"
	LogUserLoginFailed          = "user login failed: username=%s"
	LogUserProfileUpdated       = "user profile updated: user_id=%d"
	LogOrgRegisterSuccess       = "organization registered: name=%s"
	LogOrgRegisterFailed        = "organization register failed: name=%s"
	LogOrgReviewSuccess         = "organization review updated: id=%d status=%s"
	LogOrgReviewFailed          = "organization review failed: id=%d"
	LogPetPublishSuccess        = "pet published: name=%s species=%s"
	LogPetPublishFailed         = "pet publish failed: name=%s"
	LogPetStatusChanged         = "pet status changed: id=%d status=%s"
	LogPetListSuccess           = "pet list success: species=%s status=%s page=%d"
	LogAppSubmitSuccess         = "adoption application submitted: id=%d pet_id=%d"
	LogAppSubmitFailed          = "adoption application submit failed: pet_id=%d"
	LogAppStatusChanged         = "application status changed: id=%d status=%s"
	LogAppStatusChangeFailed    = "application status change failed: id=%d"
	LogReviewCreateSuccess      = "visit review created: application_id=%d"
	LogReviewSubmitSuccess      = "visit review submitted: id=%d"
	LogReviewOverdueMarked      = "visit review marked overdue: id=%d"
	LogPostCreateSuccess        = "community post created: title=%s"
	LogPostCreateFailed         = "community post create failed: title=%s"
	LogPostLikeSuccess          = "community post liked: id=%d"
	LogCommentCreateSuccess     = "post comment created: post_id=%d"
	LogDonationCreateSuccess    = "donation created: amount=%s org_id=%d"
	LogDonationCreateFailed     = "donation create failed: org_id=%d"
	LogUsageCreateSuccess       = "donation usage created: org_id=%d"
	LogFavoriteAddSuccess       = "favorite added: user_id=%d target=%s:%d"
	LogUploadSuccess            = "file upload success: object=%s"
	LogUploadFailed             = "file upload failed: filename=%s"
	LogRateLimited              = "request rate limited: path=%s ip=%s"
	LogRequestHandled           = "request handled: request_id=%s method=%s path=%s status=%d latency_ms=%d"
)
